### ISSUE TITLE
Should images and comments query be inside file? 

### ISSUE THREAD

**Issue by braposo** [braposo/figma-graphql#3]
I think it's a bit confusing to be able to do 

```gql
{
    comments(id: "KViUntEBJqK4gWfiwft5NObl") {
        ...
    }
}
```

and 

```gql
{
    image(id: "KViUntEBJqK4gWfiwft5NObl") {
        images
    }
}
```

instead of something like

```gql
{
    file(id: "KViUntEBJqK4gWfiwft5NObl") {
		image
		comments {
			...
		}
	}
}
```

I think Figma API might need some level of abstraction so it's easier and more logical to the user.

Something to think about!

**Comment by braposo** [comment]
@SaraVieira sorry I never replied to you but I'm putting this for v2.0 as I've already started doing some work in this direction. I'll let you know once I have more stuff to show you!

**Comment by okonet** [comment]
I agree it's a bit confusing and feels(at least imo) going against the GraphQL idea.
