### ISSUE TITLE
Embed Team -> Project[] -> File[]

### ISSUE THREAD

**Issue by jongold** [braposo/figma-graphql#4]
Hey Bernardo!

I'm trying to query for e.g. all of the files within a team, and with the Figma API returning truncated objects there's a lot of REST call stitching to be done. Would be so cool if we used graphql to write queries like

```graphql
{
  team(id: "123") {
    projects {
      edges {
        node {
          id
          name
          files {
            edges {
              node {
                # full FileResponse here, not the truncated version
                document {
                  # full document
                }
                name
                lastModified
              }
            }
          }
        }
      }
    }
  }
}

```

Is this something you've considered?

**Comment by braposo** [comment]
Hey @jongold, I'm really sorry for the late reply but just didn't get any notification about this so completely missed it.

I'm going to have a look at this as soon as possible as I'm not very familiar with the projects/files structure in the Figma API response. It does seem like a good use-case for graphql as it would make it simpler for the user while hiding the multiple REST requests behind the resolvers. 

I'm starting to have some free time to work on v2 (https://github.com/braposo/figma-graphql/milestone/1), which I want it to be about improving the experience of querying the Figma API so this can definitely be something to add to it.

Have you gone any further with this in the meantime?

**Comment by braposo** [comment]
@jongold it took a bit more time than expected but this has now landed! 

The API has been improved/simplified a lot so the actual query is a bit different from your comment but you can do everything you wanted:

```gql
{
  projects(teamId: "123") {
    id
    name
    files {
      name
    }
  }
}
```
