### ISSUE TITLE
Demo broken?

### ISSUE THREAD

**Issue by Wolfr** [braposo/figma-graphql#5]
Is it me or is the demo at https://www.graphqlbin.com/v2/j2LQcn broken?

<img width="886" alt="screen shot 2018-06-21 at 22 16 20" src="https://user-images.githubusercontent.com/12690/41743332-bcd7247e-75a0-11e8-9d55-0f7471cf8976.png">

(Trying out the Figma API and stumbled upon this project!)

**Comment by braposo** [comment]
hey @Wolfr, yeah it seems that one is broken for some reason, thanks for pointing out!

You can use https://graphqlbin.com/v2/D113i3 or even https://figma-graphql-pyzwnymqiy.now.sh/ directly. 

I'm working on some changes so I'll update the README too.

**Comment by Wolfr** [comment]
This works I was able to query my file, cool 👍

Do you know if there is a way to request PNG urls through this method?

I got started with this simple query:

````
{
    file(id: "xxx") {
        name
    		pages {
          name,
          id,
          frames {
            name,
            id
          }
        }
  }
}
````

**Comment by braposo** [comment]
@Wolfr for the images you actually have to query that separately right now. A more detailed explanation is available in this section of the readme: https://github.com/braposo/figma-graphql#get-just-the-image-of-a-node-a-file-or-the-whole-file

You'll need to do something like:

```gql
{
  images(id: "xxx") {
    images 
  }
}
```

In v2.0 you'll be able to get the images like you were trying to do, by querying inside a frame/page/file (syntax might not be exactly this one):
```gql
{
    file(id: "xxx") {
        name
    	pages {
        	name
          	id
          	frames {
            	name
            	id
				images
          	}
        }
  	}
}
```

**Comment by Wolfr** [comment]
Thanks so much!

Maybe unrelated but do you also have trouble getting a proper 2x quality image out of the API? I just get a relatively low-res image regardless of the scale setting.

````{
    image(id: "xxx", params: { ids: "xxx", scale: 2, format: "jpg"  }) {
        images
    }
}````

Setting to .png doesn't help either

**Comment by braposo** [comment]
@Wolfr we rely on Figma's API exporting capabilities to get that so I haven't really tested it extensively. Maybe you also need to bust the cache that is running on that demo page. I put that in place just to avoid people using it too much.

If you go to https://figma-graphql-pyzwnymqiy.now.sh/clear/KViUntEBJqK4gWfiwft5NObl (just replace this last bit with the id of your file) it will bust the cache and make a fresh request. That might be the reason why you're always getting the same image. Maybe getting a 2x image and making it 50% smaller after will solve your problem?

**Comment by Wolfr** [comment]
Busting the cache seems to do the trick 👍

**Comment by braposo** [comment]
Cool! I've also updated the README file so I'm closing this then 😄
